name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker pull hello-world:latest

      - name: Create volume
        run: docker volume create my-volume

      - name: Create network
        run: docker network create my-network

      - name: Deploy
        run: docker run -d --name my-app-container -v my-volume:/app/data --network my-network hello-world:latest sh -c "echo 'Hello, World!' > /app/test-results/file.txt"

      - name: Display contents
        run: docker run -d --name my-app-container -v my-volume:/app/data --network my-network cat /app/test-results/file.txt
